#!/usr/bin/env bash

. ./common.sh

NAME_STRING="THREADS: SIMPLE"
PARAMS="${INTERACTIVE} -heartbeat_print_pcs 1000 -perfect-l1d"
BENCHMARK="simple"

${MAKE} clean -s && ${MAKE} -s

THREADS=2
$RIGELSIM -threads ${THREADS} $PARAMS $BENCHMARK.tasks 1> /dev/null 2> /dev/null
cat RUN_OUTPUT/rigelprint.out | sed 's/0x[0-9a-f]* (PC 0x[0-9a-f]*)//' > RUN_OUTPUT/compare.out
if(diff RUN_OUTPUT/compare.out rigelprint.mt${THREADS}.GOLD) then
  echo "===== Passed ($NAME_STRING Threads $THREADS) ====="
else
  echo "===== Failed ($NAME_STRING Threads $THREADS) ====="
fi

${MAKE} clean -s && ${MAKE} -s

THREADS=4
$RIGELSIM -threads ${THREADS} $PARAMS  $BENCHMARK.tasks 1>1out 2>2out #1> /dev/null 2> /dev/null
cat RUN_OUTPUT/rigelprint.out | sed 's/0x[0-9a-f]* (PC 0x[0-9a-f]*)//' > RUN_OUTPUT/compare.out
if(diff RUN_OUTPUT/compare.out rigelprint.mt${THREADS}.GOLD) then
  echo "===== Passed ($NAME_STRING Threads $THREADS) ====="
else
  echo "===== Failed ($NAME_STRING Threads $THREADS) ====="
fi
