#!/usr/bin/env bash

source ../../common.sh

${MAKE} clean && ${MAKE}

BENCHMARK=syscalls.tasks
NAME_STRING="Syscalls (non_rtm)"
CLUSTERS=1
TEST_STRING="$CLUSTERS cluster"
STDIN_INPUT="123456 3.14159 HelloFromSTDIN"
STDOUT_FILE="syscalls.stdout.out"
ARGS="-tstdout $STDOUT_FILE"
echo "$STDIN_INPUT" | $RIGELSIM $ARGS -clusters $CLUSTERS $BENCHMARK 2> cout.out 1> cerr.out 
if (diff $STDOUT_FILE syscalls.stdout.out.GOLD > diff.out) then
   passed "===== Passed ($NAME_STRING $TEST_STRING) ====="
else
   failed "===== Failed ($NAME_STRING $TEST_STRING) ====="
fi
