#!/usr/bin/env bash

source ../../common.sh

${MAKE} clean -s && ${MAKE} -s

BENCHMARK=mvm.tasks
NAME_STRING="MVM (non_rtm)"

# THREADS=1
# CLUSTERS=1
# TEST_STRING="threads: ${THREADS} clusters: ${CLUSTERS}"
# ${RIGELSIM} -threads $THREADS -clusters $CLUSTERS ${BENCHMARK} 2> cerr.out 1> cout.out
# cat RUN_OUTPUT/rigelprint.out | sed 's/0x[0-9a-f]* (PC 0x[0-9a-f]*)//' | sed 's/ thread: [0-9]*//' > RUN_OUTPUT/compare.out ;
# if(diff RUN_OUTPUT/compare.out rigelprint.out.GOLD) then
#   echo "===== Passed ($NAME_STRING, $TEST_STRING) ====="
# else
#   echo "===== Failed ($NAME_STRING, $TEST_STRING) ====="
# fi

THREADS=1
CLUSTERS=4
TEST_STRING="threads: ${THREADS} clusters: ${CLUSTERS}"
${RIGELSIM} -threads $THREADS -clusters $CLUSTERS ${BENCHMARK} 2> threads_${THREADS}.out 1> cout.out
cat RUN_OUTPUT/rigelprint.out | sed 's/0x[0-9a-f]* (PC 0x[0-9a-f]*)//' | sed 's/ thread: [0-9]*//' > RUN_OUTPUT/compare.out ;
if (diff RUN_OUTPUT/compare.out rigelprint.out.GOLD > mt1diff.out ) then
  passed "===== Passed ($NAME_STRING $TEST_STRING) ====="
else
  #echo -e "\E[31;40m===== Failed ($NAME_STRING $TEST_STRING) ====="
  failed "===== Failed ($NAME_STRING $TEST_STRING) ====="
fi
