#!/usr/bin/env bash

source ../../common.sh

${MAKE} clean && ${MAKE}
TEST_SRC="dmm.tasks"
NAME_STRING="DMM (RTM)"
SIZE="0 64 64 64"
ARGS="-model-contention-off"
#ARGS=" -heartbeat_print_pcs 10000"

THREADS=1
CLUSTERS=2
TEST_STRING="$THREADS threads $CLUSTERS clusters"
echo ${SIZE} | $RIGELSIM $ARGS -threads $THREADS -clusters $CLUSTERS $TEST_SRC 1> cout${THREADS}.out 2> cerr${THREADS}.out 
cat RUN_OUTPUT/rigelprint.out | sed 's/0x[0-9a-f]* (PC 0x[0-9a-f]*)//' > RUN_OUTPUT/compare.out
if(diff RUN_OUTPUT/compare.out rigelprint.out.GOLD > mtdiff.out) then
  echo "===== Passed ($NAME_STRING $TEST_STRING) ====="
else
  echo "===== Failed ($NAME_STRING $TEST_STRING) ====="
fi

THREADS=2
CLUSTERS=2
TEST_STRING="$THREADS threads $CLUSTERS clusters"
echo ${SIZE} | $RIGELSIM $ARGS -threads $THREADS -clusters $CLUSTERS $TEST_SRC 1> cout${THREADS}.out 2> cerr${THREADS}.out
cat RUN_OUTPUT/rigelprint.out | sed 's/0x[0-9a-f]* (PC 0x[0-9a-f]*)//' > RUN_OUTPUT/compare.out
if(diff RUN_OUTPUT/compare.out rigelprint.out.GOLD > mtdiff.out) then
  echo "===== Passed ($NAME_STRING $TEST_STRING) ====="
else
  echo "===== Failed ($NAME_STRING $TEST_STRING) ====="
fi

THREADS=4
CLUSTERS=1
TEST_STRING="$THREADS threads $CLUSTERS clusters"
echo ${SIZE} | $RIGELSIM $ARGS -threads $THREADS -clusters $CLUSTERS $TEST_SRC 1> cout${THREADS}.out 2> cerr${THREADS}.out
cat RUN_OUTPUT/rigelprint.out | sed 's/0x[0-9a-f]* (PC 0x[0-9a-f]*)//' > RUN_OUTPUT/compare.out
if(diff RUN_OUTPUT/compare.out rigelprint.out.GOLD > mtdiff.out) then
  echo "===== Passed ($NAME_STRING $TEST_STRING) ====="
else
  echo "===== Failed ($NAME_STRING $TEST_STRING) ====="
fi

