#!/usr/bin/env bash

source ../../common.sh

${MAKE} clean && ${MAKE}

BENCHMARK=mvm.tasks
NAME_STRING="SimpleTest non_rtm"
ARGS=""
#ARGS="-regfile-trace-dump -n 1000000"

CLUSTERS=4
TEST_STRING="clusters: ${CLUSTERS}"
$RIGELSIM $ARGS -clusters $CLUSTERS simple_test.tasks 1> cout.out 2> cerr.out
cat RUN_OUTPUT/rigelprint.out | sed 's/0x[0-9a-f]* (PC 0x[0-9a-f]*)//' | sed 's/ thread: [0-9]*//' > RUN_OUTPUT/compare.out ;
if(diff RUN_OUTPUT/compare.out rigelprint.out.GOLD > diff.out) then
  echo "===== Passed ===== ($NAME_STRING,$TEST_STRING)"
else
  echo "===== Failed ===== ($NAME_STRING,$TEST_STRING)"
fi
