#!/usr/bin/env bash

. ./common

#OUTPUT=""
FOUT=fout #"/dev/null"
FERR=ferr #"/dev/null"
PARAMS="${INTERACTIVE} -heartbeat_print_pcs 1000 -perfect-l1i"

BENCHMARK="trivial"

THREADS=2
NAME_STRING="$BENCHMARK (threads: ${THREADS})"
$RIGELSIM -threads $THREADS $PARAMS $BENCHMARK.tasks 1> $FOUT 2> $FERR
cat RUN_OUTPUT/rigelprint.out | sed 's/0x[0-9a-f]* (PC 0x[0-9a-f]*)//' | sed 's/ core: [0-9]* thread: [0-9]*//' > RUN_OUTPUT/compare.out
if(diff RUN_OUTPUT/compare.out rigelprint.mt${THREADS}.GOLD) then
  echo "===== Passed ($NAME_STRING) ====="
else
  echo "===== Failed ($NAME_STRING) ====="
fi

# make clean -s && make -s
# 
# THREADS=4
# NAME_STRING="$BENCHMARK (threads: ${THREADS})"
# $RIGELSIM -threads $THREADS $BENCHMARK.tasks 1> $FOUT 2> $FERR
# cat RUN_OUTPUT/rigelprint.out | sed 's/0x[0-9a-f]* (PC 0x[0-9a-f]*)//' | sed 's/ core: [0-9]* thread: [0-9]*//' > RUN_OUTPUT/compare.out
# if(diff RUN_OUTPUT/compare.out rigelprint.mt${THREADS}.GOLD) then
#   echo "===== Passed ($NAME_STRING) ====="
# else
#   echo "===== Failed ($NAME_STRING) ====="
# fi
