RandomLib: std Namespace Reference
std Namespace Reference
Functions
template<class Generator >
void swap (RandomLib::RandomCanonical< Generator > &r, RandomLib::RandomCanonical< Generator > &s) throw ()
template<class Algorithm , class Mixer >
void swap (RandomLib::RandomEngine< Algorithm, Mixer > &r, RandomLib::RandomEngine< Algorithm, Mixer > &s) throw ()
Function Documentation
template<class Generator > void std::swap (RandomLib::RandomCanonical< Generator > & r, RandomLib::RandomCanonical< Generator > & s) throw ()
Swap two RandomCanonicals. This is about 3x faster than the default swap.
Definition at line 1281 of file RandomCanonical.hpp.
Referenced by coverage32(), coverage64(), and RandomLib::RandomEngine< Algorithm, Mixer >::swap().
template<class Algorithm , class Mixer > void std::swap (RandomLib::RandomEngine< Algorithm, Mixer > & r, RandomLib::RandomEngine< Algorithm, Mixer > & s) throw ()
Swap two RandomEngines. This is about 3x faster than the default swap.
Template Parameters:
Algorithm the algorithm for the RandomEngine.
Mixer the mixer for the RandomEngine.
Parameters:
[in,out] r the first RandomEngine to swap.
[in,out] s the second RandomEngine to swap.
Definition at line 627 of file RandomEngine.hpp.