RandomLib: RandomThread.cpp File Reference
RandomThread.cpp File Reference
Example of parallelization with RandomLib using threads.
#include <iostream>
#include <iomanip>
#include <limits>
#include <vector>
#include <string>
#include <sstream>
#include <numeric>
#include <RandomLib/Random.hpp>
Functions
double dotrials (Random &r, int d, long long n)
double result (int d, long long n, double w)
int usage (const std::string &name, int retval)
int main (int argc, char *argv[])
Detailed Description
Example of parallelization with RandomLib using threads.
Compile/link with, e.g.,
g++ -I../include -O2 -funroll-loops -fopenmp -o RandomThread RandomThread.cpp ../src/Random.cpp
./RandomThread
Id:
30e9c3974e94e95b899af0ab868584874708fcf4
See Parallelization, for a description of this example.
Copyright (c) Charles Karney (2011) <charles@karney.com> and licensed under the MIT/X11 License. For more information, see http://randomlib.sourceforge.net/
Definition in file RandomThread.cpp.
Function Documentation
double dotrials (Random & r, int d, long long n)
Definition at line 34 of file RandomThread.cpp.
Referenced by main().
double result (int d, long long n, double w)
Definition at line 51 of file RandomThread.cpp.
Referenced by main().
int usage (const std::string & name, int retval)
Definition at line 57 of file RandomThread.cpp.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 65 of file RandomThread.cpp.
References dotrials(), result(), and usage().