RandomLib: RandomCoverage.cpp File Reference
RandomCoverage.cpp File Reference
Coverage test for RandomLib.
#include <iostream>
#include <vector>
#include <string>
#include <sstream>
#include <RandomLib/Random.hpp>
#include <RandomLib/NormalDistribution.hpp>
#include <RandomLib/ExponentialDistribution.hpp>
#include <RandomLib/RandomSelect.hpp>
#include <RandomLib/LeadingZeros.hpp>
#include <RandomLib/ExponentialProb.hpp>
#include <RandomLib/RandomNumber.hpp>
#include <RandomLib/ExactExponential.hpp>
#include <RandomLib/ExactNormal.hpp>
#include <RandomLib/ExactPower.hpp>
Defines
#define repeat for (int i = 0; i < 1000; ++i)
Functions
void coverage32 ()
void coverage64 ()
int main (int, char **)
Detailed Description
Coverage test for RandomLib.
Compile/link with, e.g.,
g++ -I../include -O2 -funroll-loops -o RandomCoverage RandomCoverage.cpp ../src/Random.cpp
./RandomCoverage
This executes nearly all of the public functions in RandomLib. This is important, since it allows the compiler to check the code which appears in header files. It also shows how templated functions can be invoked.
Id:
d7447c8c9999b14028b8e0fd30a62f30bd193927
Copyright (c) Charles Karney (2006-2011) <charles@karney.com> and licensed under the MIT/X11 License. For more information, see http://randomlib.sourceforge.net/
Definition in file RandomCoverage.cpp.
Define Documentation
#define repeat for (int i = 0; i < 1000; ++i)
Definition at line 36 of file RandomCoverage.cpp.
Referenced by coverage32(), and coverage64().
Function Documentation
void coverage32 ()
Definition at line 38 of file RandomCoverage.cpp.
References RandomLib::RandomNumber< bits >::AddInteger(), RandomLib::RandomNumber< bits >::Digit(), RandomLib::RandomNumber< bits >::Fraction(), RandomLib::RandomNumber< bits >::Init(), RandomLib::RandomSelect< NumericType >::Init(), RandomLib::RandomNumber< bits >::Integer(), RandomLib::RandomNumber< bits >::LessThan(), RandomLib::RandomNumber< bits >::Negate(), RandomLib::RandomNumber< bits >::Range(), RandomLib::RandomNumber< bits >::RawDigit(), repeat, RandomLib::RandomNumber< bits >::SetInteger(), RandomLib::RandomNumber< bits >::Size(), std::swap(), and RandomLib::RandomNumber< bits >::Value().
Referenced by main().
void coverage64 ()
Definition at line 234 of file RandomCoverage.cpp.
References RandomLib::RandomNumber< bits >::AddInteger(), RandomLib::RandomNumber< bits >::Digit(), RandomLib::RandomNumber< bits >::Fraction(), RandomLib::RandomNumber< bits >::Init(), RandomLib::RandomSelect< NumericType >::Init(), RandomLib::RandomNumber< bits >::Integer(), RandomLib::RandomNumber< bits >::LessThan(), RandomLib::RandomNumber< bits >::Negate(), RandomLib::RandomNumber< bits >::Range(), RandomLib::RandomNumber< bits >::RawDigit(), repeat, RandomLib::RandomNumber< bits >::SetInteger(), RandomLib::RandomNumber< bits >::Size(), std::swap(), and RandomLib::RandomNumber< bits >::Value().
Referenced by main().
int main (int , char **)
Definition at line 430 of file RandomCoverage.cpp.
References coverage32(), coverage64(), RandomLib::RandomEngine< Algorithm, Mixer >::Name(), and RandomLib::RandomEngine< Algorithm, Mixer >::SetCount().