#!/usr/bin/env bash

source ../../common.sh

${MAKE} clean && ${MAKE}

ARGS="-model-contention-off"

echo "0 test.bin" | $RIGELSIM ${ARGS} -clusters 2 cg.tasks 1> cout.out 2> cerr.out 
# Use sed to extract out all by the N-2 most-significant digits of the FP result.
cat RUN_OUTPUT/rigelprint.out | sed 's/0x[0-9a-f]* (PC 0x[0-9a-f]*).*(\(.*\)[0-9]\{2\} f).*/\1/' > RUN_OUTPUT/compare.out
if(diff RUN_OUTPUT/compare.out rigelprint.out.GOLD > diff.out) then
  passed "===== Passed ===== (Benchmark: RTM CG)"
else
  failed "===== Failed ===== (Benchmark: RTM CG)"
fi
